apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: altinnkanal-2
  namespace: default
  labels:
    team: integrasjon
spec:
  image: repo.adeo.no:5443/integrasjon/altinnkanal-2:@@VERSION@@
  port: 8080
  team: integrasjon
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  liveness:
    path: /internal/is_alive
    timeout: 1
    initialDelay: 30
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /internal/is_ready
    initialDelay: 20
    timeout: 1
  leaderElection: false
  prometheus:
    enabled: true
    path: /internal/prometheus
  istio:
    enabled: false
  resources:
    limits:
      cpu: 250m
      memory: 600Mi
    requests:
      cpu: 50m
      memory: 200Mi
  secrets: true
