routes:
  - topic: aapen-altinn-bankkontonummer-Mottatt
    serviceCode: 2896
    serviceEditionCode: 87
  - topic: aapen-altinn-oppfolgingsplan-Mottatt
    serviceCode: 2913
    serviceEditionCode: 2
  - topic: aapen-altinn-oppfolgingsplan-Mottatt
    serviceCode: 2913
    serviceEditionCode: 3
  - topic: aapen-altinn-oppfolgingsplan-Mottatt
    serviceCode: 2913
    serviceEditionCode: 4
  - topic: aapen-altinn-oppfolgingsplan-Mottatt
    serviceCode: NavOppfPlan
    serviceEditionCode: rapportering-sykmeldte
  - topic: aapen-altinn-maalekort-Mottatt
    serviceCode: 4711
    serviceEditionCode: 1
  - topic: aapen-altinn-barnehageliste-Mottatt
    serviceCode: 4795
    serviceEditionCode: 1
  - topic: aapen-altinn-inntektsskjema-Mottatt
    serviceCode: 4936
    serviceEditionCode: 1
  - topic: aapen-altinn-inntektsskjema-Mottatt
    serviceCode: 4936
    serviceEditionCode: 2
